### ISSUE TITLE
itypes lacks a LICENSE file

### ISSUE THREAD

**Issue by werwty** [tomchristie/itypes#4]
Hi tomchristie,
I'm working on packaging coreapi and all dependencies (one of which is itypes) for fedora. I see that itypes is licensed under BSD in pypi, could you please add the bsd license file to itypes so I can include it in the package?

**Comment by sannykr** [comment]
Please add a license file

**Comment by sannykr** [comment]
@tomchristie: I am trying to push this package to conda-forge, but you haven't added the license. Can you please add that.

**Comment by k-dominik** [comment]
Hey @sannykr, @tomchristie , i haven't checked here first, only on conda-forge and have submitted a [PR to add this package](https://github.com/conda-forge/staged-recipes/pull/5324) . And yep, they do require a LICENSE file. So it would be highly appreciated if #10  could be merged.

**Comment by sannykr** [comment]
@tomchristie : following up

**Comment by scopatz** [comment]
Can you still please add a license for those who are looking to use coreapi?

**Comment by tomchristie** [comment]
Resolved.

**Comment by scopatz** [comment]
Thanks
